
server:
  applicationConnectors:
    - type: http
      port: 8084
  adminConnectors:
    - type: http
      port: 8085

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
  appenders:
    - type: console

#
